---
services:
  cups:
    image: grandow/cups:2.4.12-office
    container_name: cups
    restart: unless-stopped
    ulimits:
        nofile:
          soft: "65536"
          hard: "65536"
    ports:
        - "631:631"
        - "5353:5353/udp"
    environment:
        - USERNAME=admin
        - PASSWORD=cups
        - TZ="America/Sao_Paulo"
    volumes:
        - "/srv/waprint/cups/:/etc/cups/"
